// Generated by CoffeeScript 1.9.2
(function() {
  Restivus.configure({
    useAuth: true,
    prettyJson: true,
    auth: {
      token: 'services.resume.loginTokens.token',
      user: function() {
        return {
          userId: this.request.headers['x-user-id'],
          token: this.request.headers['x-auth-token']
        };
      }
    },
    onLoggedIn: function() {
      return console.log(this.user.username + " (" + this.userId + ") logged in");
    },
    onLoggedOut: function() {
      return console.log(this.user.username + " (" + this.userId + ") logged out");
    }
  });

}).call(this);

//# sourceMappingURL=rest_settings.js.map
